services:
  - type: web
    name: tao10-backend
    runtime: docker
    dockerfilePath: ./TaO10-BackEnd/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: tao10-api
      - key: Jwt__Audience
        value: tao10-client
      - key: CORS_ALLOWED_ORIGINS
        value: https://tao10m.com,https://tao10.pages.dev,https://tao10-frontends.pages.dev,http://localhost:4200
      - key: Gemini__ApiKey
        sync: false
      - key: SmtpSettings__SenderEmail
        sync: false
      - key: SmtpSettings__BrevoApiKey
        sync: false
      - key: PayOS__ClientId
        sync: false
      - key: PayOS__ApiKey
        sync: false
      - key: PayOS__ChecksumKey
        sync: false
