// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaO10_BackEnd.Models;

#nullable disable

namespace TaO10_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622103129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaO10_BackEnd.Models.BlogPost", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("blog_post_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int?>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.HasKey("BlogPostId")
                        .HasName("blog_posts_pkey");

                    b.HasIndex("StatusId");

                    b.ToTable("blog_posts", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Exam", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int?>("AttemptsCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempts_count");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationTime")
                        .HasColumnType("integer")
                        .HasColumnName("duration_time");

                    b.Property<string>("ExamType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exam_type");

                    b.Property<string>("Level")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("level");

                    b.Property<int?>("QuestionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("questions_count");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("ExamId")
                        .HasName("exams_pkey");

                    b.HasIndex("StatusId");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.ForumCategory", b =>
                {
                    b.Property<Guid>("ForumCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("forum_category_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Badge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("badge");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("RepliesCount")
                        .HasColumnType("integer")
                        .HasColumnName("replies_count");

                    b.Property<int?>("ThreadsCount")
                        .HasColumnType("integer")
                        .HasColumnName("threads_count");

                    b.HasKey("ForumCategoryId")
                        .HasName("forum_categories_pkey");

                    b.ToTable("forum_categories", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.ForumReply", b =>
                {
                    b.Property<Guid>("ForumReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("forum_reply_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ForumThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_thread_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ForumReplyId")
                        .HasName("forum_replies_pkey");

                    b.HasIndex("ForumThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("forum_replies", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.ForumThread", b =>
                {
                    b.Property<Guid>("ForumThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("forum_thread_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<Guid?>("ForumCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_category_id");

                    b.Property<bool?>("IsHot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hot");

                    b.Property<bool?>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<int?>("RepliesCount")
                        .HasColumnType("integer")
                        .HasColumnName("replies_count");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.HasKey("ForumThreadId")
                        .HasName("forum_threads_pkey");

                    b.HasIndex("ForumCategoryId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("forum_threads", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Package", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("package_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationTime")
                        .HasColumnType("integer")
                        .HasColumnName("duration_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PackageId")
                        .HasName("packages_pkey");

                    b.HasIndex("StatusId");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.PackageExam", b =>
                {
                    b.Property<Guid>("PackageExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("package_exam_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.HasKey("PackageExamId")
                        .HasName("package_exams_pkey");

                    b.HasIndex("ExamId");

                    b.HasIndex(new[] { "PackageId", "ExamId" }, "package_exams_package_id_exam_id_key")
                        .IsUnique();

                    b.ToTable("package_exams", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("ResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reset_token_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_time");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ResetTokenId")
                        .HasName("password_reset_tokens_pkey");

                    b.HasIndex(new[] { "UserId", "OtpCode" }, "uk_user_otp")
                        .IsUnique();

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ExpectedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("expected_amount");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<int?>("ReceivedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("received_amount");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("payments_pkey");

                    b.HasIndex("PackageId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("question_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("OptionA")
                        .HasColumnType("text")
                        .HasColumnName("option_a");

                    b.Property<string>("OptionB")
                        .HasColumnType("text")
                        .HasColumnName("option_b");

                    b.Property<string>("OptionC")
                        .HasColumnType("text")
                        .HasColumnName("option_c");

                    b.Property<string>("OptionD")
                        .HasColumnType("text")
                        .HasColumnName("option_d");

                    b.Property<decimal?>("Points")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("points");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("question_number");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.HasKey("QuestionId")
                        .HasName("questions_pkey");

                    b.HasIndex("ExamId");

                    b.HasIndex("StatusId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool?>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshTokenId")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Status", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("status_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.HasKey("StatusId")
                        .HasName("statuses_pkey");

                    b.HasIndex(new[] { "EntityType", "Code" }, "statuses_entity_type_code_key")
                        .IsUnique();

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<int?>("TotalExams")
                        .HasColumnType("integer")
                        .HasColumnName("total_exams");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "users_phone_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("UserAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_answer_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("AnsweredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<char?>("UserAnswer1")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("user_answer");

                    b.Property<Guid?>("UserExamAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_exam_attempt_id");

                    b.HasKey("UserAnswerId")
                        .HasName("user_answers_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserExamAttemptId");

                    b.ToTable("user_answers", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserExamAttempt", b =>
                {
                    b.Property<Guid>("UserExamAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_exam_attempt_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<int?>("TimeSpentMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_minutes");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserExamAttemptId")
                        .HasName("user_exam_attempts_pkey");

                    b.HasIndex("ExamId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("user_exam_attempts", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserPackage", b =>
                {
                    b.Property<Guid>("UserPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_package_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserPackageId")
                        .HasName("user_packages_pkey");

                    b.HasIndex("PackageId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("user_packages", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserProgress", b =>
                {
                    b.Property<Guid>("UserProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_progress_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_type");

                    b.Property<DateTime?>("LastAccessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserProgressId")
                        .HasName("user_progress_pkey");

                    b.HasIndex(new[] { "UserId", "ItemType", "ItemId" }, "user_progress_user_id_item_type_item_id_key")
                        .IsUnique();

                    b.ToTable("user_progress", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserStudyRoadmap", b =>
                {
                    b.Property<Guid>("UserStudyRoadmapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_study_roadmap_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DailyTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("daily_time");

                    b.Property<string>("NextAction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("next_action");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("strengths");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserExamAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_exam_attempt_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weaknesses");

                    b.Property<string>("Weeks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weeks");

                    b.HasKey("UserStudyRoadmapId")
                        .HasName("user_study_roadmaps_pkey");

                    b.HasIndex("UserExamAttemptId");

                    b.HasIndex(new[] { "UserId" }, "ix_user_study_roadmaps_user_id")
                        .IsUnique();

                    b.ToTable("user_study_roadmaps", (string)null);
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.BlogPost", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("BlogPosts")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("blog_posts_status_id_fkey");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Exam", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("Exams")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("exams_status_id_fkey");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.ForumReply", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.ForumThread", "ForumThread")
                        .WithMany("ForumReplies")
                        .HasForeignKey("ForumThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("forum_replies_forum_thread_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("ForumReplies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("forum_replies_user_id_fkey");

                    b.Navigation("ForumThread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.ForumThread", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.ForumCategory", "ForumCategory")
                        .WithMany("ForumThreads")
                        .HasForeignKey("ForumCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("forum_threads_forum_category_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("ForumThreads")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("forum_threads_status_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("ForumThreads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("forum_threads_user_id_fkey");

                    b.Navigation("ForumCategory");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Notification", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Package", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("Packages")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("packages_status_id_fkey");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.PackageExam", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Exam", "Exam")
                        .WithMany("PackageExams")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("package_exams_exam_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.Package", "Package")
                        .WithMany("PackageExams")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("package_exams_package_id_fkey");

                    b.Navigation("Exam");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.PasswordResetToken", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("password_reset_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Payment", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Package", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_package_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("payments_status_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("payments_user_id_fkey");

                    b.Navigation("Package");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Question", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("questions_exam_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("Questions")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("questions_status_id_fkey");

                    b.Navigation("Exam");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.RefreshToken", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.User", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("users_status_id_fkey");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserAnswer", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_answers_question_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.UserExamAttempt", "UserExamAttempt")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("user_answers_user_exam_attempt_id_fkey");

                    b.Navigation("Question");

                    b.Navigation("UserExamAttempt");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserExamAttempt", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Exam", "Exam")
                        .WithMany("UserExamAttempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_exam_attempts_exam_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("UserExamAttempts")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("user_exam_attempts_status_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("UserExamAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_exam_attempts_user_id_fkey");

                    b.Navigation("Exam");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserPackage", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.Package", "Package")
                        .WithMany("UserPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_packages_package_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.Payment", "Payment")
                        .WithMany("UserPackages")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_packages_payment_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.Status", "Status")
                        .WithMany("UserPackages")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("user_packages_status_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("UserPackages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_packages_user_id_fkey");

                    b.Navigation("Package");

                    b.Navigation("Payment");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserProgress", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_progress_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserStudyRoadmap", b =>
                {
                    b.HasOne("TaO10_BackEnd.Models.UserExamAttempt", "UserExamAttempt")
                        .WithMany()
                        .HasForeignKey("UserExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_study_roadmaps_user_exam_attempt_id_fkey");

                    b.HasOne("TaO10_BackEnd.Models.User", "User")
                        .WithMany("UserStudyRoadmaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_study_roadmaps_user_id_fkey");

                    b.Navigation("User");

                    b.Navigation("UserExamAttempt");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Exam", b =>
                {
                    b.Navigation("PackageExams");

                    b.Navigation("Questions");

                    b.Navigation("UserExamAttempts");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.ForumCategory", b =>
                {
                    b.Navigation("ForumThreads");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.ForumThread", b =>
                {
                    b.Navigation("ForumReplies");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Package", b =>
                {
                    b.Navigation("PackageExams");

                    b.Navigation("Payments");

                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Payment", b =>
                {
                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Question", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.Status", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("Exams");

                    b.Navigation("ForumThreads");

                    b.Navigation("Packages");

                    b.Navigation("Payments");

                    b.Navigation("Questions");

                    b.Navigation("UserExamAttempts");

                    b.Navigation("UserPackages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.User", b =>
                {
                    b.Navigation("ForumReplies");

                    b.Navigation("ForumThreads");

                    b.Navigation("Notifications");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserExamAttempts");

                    b.Navigation("UserPackages");

                    b.Navigation("UserProgresses");

                    b.Navigation("UserStudyRoadmaps");
                });

            modelBuilder.Entity("TaO10_BackEnd.Models.UserExamAttempt", b =>
                {
                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
